import {
  BookOpen,
  CalendarClock,
  ClipboardCheck,
  ClipboardList,
  FileText,
  GraduationCap,
  LayoutDashboard,
  LifeBuoy,
  Megaphone,
  MessageSquare,
  PackageOpen,
  ScrollText,
  Settings,
  ShieldAlert,
  UserCircle,
  UserCog,
  UserCheck,
  Users
} from "lucide-react";

export const adminNavItems = [
  { href: "/", label: "Dashboard", icon: LayoutDashboard },
  { href: "/cohorts", label: "Cohorts", icon: BookOpen },
  { href: "/modules", label: "Modules", icon: PackageOpen },
  { href: "/sessions", label: "Sessions", icon: CalendarClock },
  { href: "/resources", label: "Resources", icon: FileText },
  { href: "/assignments", label: "Assignments", icon: ClipboardList },
  { href: "/students", label: "Mentees", icon: GraduationCap },
  { href: "/mentors", label: "Mentors", icon: Users },
  { href: "/admin-managers", label: "Admin Managers", icon: UserCog, roles: ["superAdmin"] },
  { href: "/bookings", label: "Bookings", icon: UserCheck },
  { href: "/reports", label: "Reports", icon: ScrollText },
  { href: "/certificates", label: "Certificates", icon: GraduationCap },
  { href: "/discussions", label: "Discussions", icon: MessageSquare },
  { href: "/announcements", label: "Announcements", icon: Megaphone },
  { href: "/notifications", label: "Notifications", icon: Megaphone, roles: ["admin", "superAdmin"] },
  { href: "/support", label: "Support Tickets", icon: LifeBuoy },
  { href: "/beta-applications", label: "Beta Applications", icon: ClipboardCheck },
  { href: "/system-logs", label: "System Logs", icon: ShieldAlert, roles: ["admin", "superAdmin"] },
  { href: "/settings", label: "Settings", icon: Settings, roles: ["admin", "superAdmin"] },
  { href: "/profile", label: "Profile", icon: UserCircle }
];
